// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "miami": {
   "accordion": {
     name: "accordion",
     description: "",
     type: "registry:ui",
     registryDependencies: undefined,
     files: [{
       path: "registry/miami/ui/accordion.tsx",
       type: "registry:component",
       target: ""
     }],
     component: React.lazy(() => import("~/registry/miami/ui/accordion.tsx")),
     source: "",
     category: "",
     subcategory: "",
     chunks: []
   },
 },  "default": {
   "accordion": {
     name: "accordion",
     description: "",
     type: "registry:ui",
     registryDependencies: undefined,
     files: [{
       path: "registry/default/ui/accordion.tsx",
       type: "registry:component",
       target: ""
     }],
     component: React.lazy(() => import("~/registry/default/ui/accordion.tsx")),
     source: "",
     category: "",
     subcategory: "",
     chunks: []
   },
 },
}
